# Generated by Django 3.2.8 on 2022-06-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('company', '0004_remove_company_passwd'),
        ('employee', '0006_alter_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_FE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('generated_date', models.TextField()),
                ('state', models.TextField(default='01010011,01101001,01101110,00100000,01100101,01101110,01110110,01101001,01100001,01110010,00100000,01100001,00100000,01101100,01100001,00100000,01000100,01001001,01000001,01001110')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_FE_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('quanty', models.TextField()),
                ('discount', models.TextField()),
                ('tax', models.TextField()),
                ('cost', models.TextField()),
                ('ico', models.TextField()),
                ('stronghold', models.TextField()),
                ('payment_method', models.TextField()),
                ('payment_due_date', models.TextField()),
                ('duration_measure', models.TextField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_fe.invoice_fe')),
            ],
        ),
    ]
