# Generated by Django 3.2.8 on 2022-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('product', models.TextField()),
                ('quanty', models.TextField()),
                ('cost', models.TextField()),
                ('utility', models.TextField()),
                ('tax', models.TextField()),
                ('price', models.TextField()),
                ('discount', models.TextField()),
                ('initial_quanty', models.TextField()),
                ('exhausted', models.TextField()),
            ],
        ),
    ]
