# Generated by Django 3.2.8 on 2022-06-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_consecutive_fe_consecutive_payroll_consecutive_pos_consecutive_supportdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='passwd',
            field=models.TextField(default=''),
        ),
    ]
