# Generated by Django 3.2.8 on 2022-06-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='passwd',
        ),
    ]
